### PR TITLE
feat(swReference): Reference SW in application

### PR DESCRIPTION
**Pull request by rishabh3112**
Refers #5 
@dhruvdutt @sendilkumarn needs guide to proceed further

### CODE REVIEW

**Comment by rishabh3112** [comment]
Have a look @dhruvdutt @sendilkumarn , 
This is intended to fix the issue #5

**Comment by sendilkumarn** [comment]
@rishabh3112 awesome 🎉 
Can you let me know what guidance you need on this?

**Comment by rishabh3112** [comment]
@sendikumarn I found some bugs while testing like:
1. Output folder is set to be `/dist` instead of `./dist`.
2. Manifest is moved in dist folder under dist folder
Can I correct them in this PR itself?

If you have a look at my 2nd commit can you suggest that the approch with I am proceeding is correct in terms of maintainability or not.

**Comment by dhruvdutt** [comment]
@rishabh3112 Nice job. :100: 

You can go ahead and fix the bugs you've identified. The fix for these looks like something which is out of scope of this PR. You can add a new PR preferably and then rebase this one.

**Comment by rishabh3112** [comment]
Any feedback on this PR @sendilkumarn @dhruvdutt ??

**Pull request merged**
